console.log("+++++++++++++++++++++")
console.log ("hello everyone")
console.log("+++++++++++++++++++++")
console.log("")
console.log("")
console.log("good morning")
console.log("----------------")
console.log("good afternoon")
console.log("----------------")
console.log("good evening")
console.log("----------------")

